#display
OF_SCREEN_H := 2400
OF_STATUS_H := 122
OF_STATUS_INDENT_LEFT := 80
OF_STATUS_INDENT_RIGHT := 80

#ui
OF_USE_GREEN_LED := 0
OF_HIDE_NOTCH := 1
OF_ALLOW_DISABLE_NAVBAR := 0
OF_OPTIONS_LIST_NUM := 12

#flashlight
OF_FLASHLIGHT_ENABLE := 0

#partition
OF_UNBIND_SDCARD_F2FS := 1
OF_QUICK_BACKUP_LIST := /boot;/data;/dtbo;/recovery;

#frp
OF_ENABLE_FRP_ADDON := 1
